language: python
python:
    - "3.6"
    - "3.5"
    - "3.4"
    - "3.3"
    - "2.7"
    - "2.6"
install:
    - "pip install -r tests/test_requirements.txt"
script:
    - nosetests --with-coverage --cover-package=pychievements
after_success:
    - coveralls
